# Generated by Django 3.0.6 on 2020-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200621_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='member',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='MEMBER'),
        ),
    ]
